---
- name: Get Vector distrib
  ansible.builtin.get_url:
    url: "{{ vector_url }}"
    dest: "/tmp/vector-{{ vector_version }}.tar.gz"
    mode: '0644'

- name: Create install directory
  become: true
  ansible.builtin.file:
    path: "{{ vector_install_dir }}"
    state: directory
    mode: '0755'

- name: Unpack Vector
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/vector-{{ vector_version }}.tar.gz"
    dest: "{{ vector_install_dir }}"
    remote_src: true
    extra_opts: ["--strip-components=1"]

- name: Create config directory
  become: true
  ansible.builtin.file:
    path: /etc/vector
    state: directory
    mode: '0755'

- name: Deploy Vector config
  become: true
  ansible.builtin.template:
    src: vector.toml.j2
    dest: /etc/vector/vector.toml
    mode: '0644'
  notify: Restart vector

- name: Find vector binary
  ansible.builtin.find:
    paths: /opt/vector
    patterns: "vector"
    recurse: true
    file_type: file
  register: vector_binary

- name: Create vector systemd service
  become: true
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Vector
      After=network.target
      [Service]
      ExecStart={{ vector_binary.files[0].path }} --config /etc/vector/vector.toml
      Restart=always
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/vector.service
    mode: '0644'

- name: Start vector
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    enabled: true
    daemon_reload: true
