---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: true
  become: false
  vars:
    clickhouse_host: "127.0.0.1"
  pre_tasks:
    - name: Create temp directory
      file:
        path: /tmp/.ansible/tmp
        state: directory
        mode: '0777'
  tasks:
    - name: Apply vector role
      ansible.builtin.include_role:
        name: vector

