---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instance_name: "{{ molecule_yml.platforms[0].name }}"
    instance_image: "{{ molecule_yml.platforms[0].image }}"
  tasks:
    - name: Create container
      community.docker.docker_container:
        name: "{{ instance_name }}"
        image: "{{ instance_image }}"
        state: started
        privileged: true
        command: sleep infinity