---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Create ansible tmp directory
      ansible.builtin.raw: |
        mkdir -p /tmp/.ansible/tmp && chmod 777 /tmp/.ansible/tmp
      changed_when: false

    - name: Install sudo and Python (Debian)
      ansible.builtin.raw: |
        apt-get update && apt-get install -y sudo python3
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Install sudo and Python (RedHat)
      ansible.builtin.raw: |
        dnf install -y sudo python3
      when: ansible_os_family == "RedHat"
      changed_when: false