---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create instance container
      community.docker.docker_container:
        name: instance
        image: aragast/netology:latest
        state: started
        privileged: true
        command: sleep infinity
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
