---
- name: Destroy
  hosts: localhost
  connection: local
  tasks:
    - name: Remove container
      community.docker.docker_container:
        name: instance
        state: absent
        force_kill: true
