---
driver:
  name: docker
platforms:
  - name: instance
    image: aragast/netology:latest
    privileged: true
    command: sleep infinity
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
  options:
    vvv: true
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
