---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Remove podman container
      containers.podman.podman_container:
        name: podman-instance
        state: absent
        force_kill: true